# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
root: false
cache: packages

os:
  - linux
  - osx

dist: bionic

r:
  - release
  - oldrel
  - devel

jobs:
  exclude:
    - os: osx
      r: devel


after_success:
  - Rscript -e 'covr::codecov()'
